FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1

# Set working dir
WORKDIR /app

# Install dependencies
COPY app/requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copy rest of app
COPY app/bot.py /app/
COPY app/slackbot_googleai.py /app/
COPY app/sample.env /app/
COPY app/Readme.md /app/

# Expose necessary port for Discord bot
EXPOSE 5000

# Run the bot
CMD ["python", "bot.py"]
